//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.12 at 05:30:38 PM SGT 
//


package com.minetool.dblp.parser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww"
})
@XmlRootElement(name = "dblp")
public class Dblp {

    @XmlElements({
        @XmlElement(name = "article", type = Article.class),
        @XmlElement(name = "inproceedings", type = Inproceedings.class),
        @XmlElement(name = "proceedings", type = Proceedings.class),
        @XmlElement(name = "book", type = Book.class),
        @XmlElement(name = "incollection", type = Incollection.class),
        @XmlElement(name = "phdthesis", type = Phdthesis.class),
        @XmlElement(name = "mastersthesis", type = Mastersthesis.class),
        @XmlElement(name = "www", type = Www.class)
    })
    protected List<Object> articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww;

    /**
     * Gets the value of the articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Article }
     * {@link Inproceedings }
     * {@link Proceedings }
     * {@link Book }
     * {@link Incollection }
     * {@link Phdthesis }
     * {@link Mastersthesis }
     * {@link Www }
     * 
     * 
     */
    public List<Object> getArticleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww() {
        if (articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww == null) {
            articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww = new ArrayList<Object>();
        }
        return this.articleOrInproceedingsOrProceedingsOrBookOrIncollectionOrPhdthesisOrMastersthesisOrWww;
    }

}
